/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.AeropuertoControlador;
import Modelos.MisExcepciones;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Administrador extends javax.swing.JDialog {

    /**
     * Creates new form Administrador
     */
    AeropuertoControlador LaNubia;

    public Administrador(java.awt.Frame parent, boolean modal, AeropuertoControlador LaNubia) {
        super(parent, modal);
        initComponents();
        this.LaNubia = LaNubia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        btnModificarPromociones = new javax.swing.JButton();
        btnCalcularGanacias = new javax.swing.JButton();
        btnVerPromociones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBienvenido.setText("Bienvenido");

        btnModificarPromociones.setText("Modificar Promociones");
        btnModificarPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPromocionesActionPerformed(evt);
            }
        });

        btnCalcularGanacias.setText("Calcular Ganancias");
        btnCalcularGanacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularGanaciasActionPerformed(evt);
            }
        });

        btnVerPromociones.setText("Ver Promociones");
        btnVerPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPromocionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalcularGanacias, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarPromociones)
                            .addComponent(btnVerPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblBienvenido)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerPromociones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarPromociones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcularGanacias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularGanaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularGanaciasActionPerformed
        try {
            JOptionPane.showMessageDialog(null, LaNubia.calcularIngresos());
        } catch (MisExcepciones ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error "+ex);
        }
    }//GEN-LAST:event_btnCalcularGanaciasActionPerformed

    private void btnVerPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPromocionesActionPerformed
        MostrarPromociones Promociones = new MostrarPromociones(null, true, this.LaNubia);
        Promociones.setVisible(true);
    }//GEN-LAST:event_btnVerPromocionesActionPerformed

    private void btnModificarPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPromocionesActionPerformed
        ModificarPromocion PromocionesM = new ModificarPromocion(null, true, this.LaNubia);
        PromocionesM.setVisible(true);
    }//GEN-LAST:event_btnModificarPromocionesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularGanacias;
    private javax.swing.JButton btnModificarPromociones;
    private javax.swing.JButton btnVerPromociones;
    private javax.swing.JLabel lblBienvenido;
    // End of variables declaration//GEN-END:variables
}
