/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.AeropuertoControlador;
import Modelos.MisExcepciones;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class AeropuertoVista extends javax.swing.JFrame {

    /**
     * Creates new form AeropuertoVista
     */
    AeropuertoControlador LaNubia = new AeropuertoControlador("LaNubia", "Manizales/Caldas", "APLaNubia@gmial.com", 8740111);

    public AeropuertoVista() {
        initComponents();
    }

    public void guardar() {
        try {
            FileOutputStream archivo = new FileOutputStream("datos.txt");
            ObjectOutputStream oos = new ObjectOutputStream(archivo);
            oos.writeObject(LaNubia);
            oos.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void cargar() {
        try {
            FileInputStream archivo = new FileInputStream("datos.txt");
            try (ObjectInputStream ois = new ObjectInputStream(archivo)) {
                LaNubia = (AeropuertoControlador) ois.readObject();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLaNubia = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        btnIniciarSesionClientes = new javax.swing.JButton();
        btnIniciarSesionAdministrador = new javax.swing.JButton();
        lblClientes = new javax.swing.JLabel();
        lblAdministrador = new javax.swing.JLabel();
        lblCargarYGuardar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLaNubia.setText("Aeropuerto La Nubia");

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        btnIniciarSesionClientes.setText("Iniciar Sesion");
        btnIniciarSesionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionClientesActionPerformed(evt);
            }
        });

        btnIniciarSesionAdministrador.setText("Iniciar Sesion Administrador");
        btnIniciarSesionAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionAdministradorActionPerformed(evt);
            }
        });

        lblClientes.setText("Clientes");

        lblAdministrador.setText("Administrador");

        lblCargarYGuardar.setText("Guardar Y Cargar Archivos");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdministrador)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIniciarSesionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIniciarSesionAdministrador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblLaNubia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblCargarYGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaNubia)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientes)
                    .addComponent(lblAdministrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarSesionAdministrador)
                    .addComponent(btnIniciarSesionClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarse)
                .addGap(35, 35, 35)
                .addComponent(lblCargarYGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        AgregarCliente formularioCliente = new AgregarCliente(this, true);
        formularioCliente.setVisible(true);
        String nombre = formularioCliente.getNombre();
        int documento = formularioCliente.getDocumento();
        String direccion = formularioCliente.getDireccion();
        String contraseña = formularioCliente.getContraseña();
        int cuentaBancaria = formularioCliente.getcuentaBancaria();
        String tipo = formularioCliente.getTipo();
        String correo = formularioCliente.getCorreo();
        int telefono = formularioCliente.getTelefono();
        try {
            LaNubia.RegistrarCliente(nombre, documento, direccion, contraseña, cuentaBancaria, tipo, correo, telefono);
        } catch (MisExcepciones ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error " + ex);
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnIniciarSesionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionClientesActionPerformed
        IniciarSesion formularioIniciarSesion = new IniciarSesion(this, true);
        formularioIniciarSesion.setVisible(true);
        int documento = formularioIniciarSesion.getDocumento();
        String contraseña = formularioIniciarSesion.getContraseña();
        int resultado;
        try {
            resultado = LaNubia.IniciarSesion(documento, contraseña);
            if (resultado == 1) {
                ClientePremium formularioInicioSesionPremium = new ClientePremium(null, true, this.LaNubia);
                formularioInicioSesionPremium.setVisible(true);
            }
            if (resultado == 2) {
                ClienteNormal formularioInicioSesionNormal = new ClienteNormal(null, true, this.LaNubia);
                formularioInicioSesionNormal.setVisible(true);
            }
            if (resultado == 0) {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado registrese");
            }
        } catch (MisExcepciones ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error " + ex);
        }

    }//GEN-LAST:event_btnIniciarSesionClientesActionPerformed

    private void btnIniciarSesionAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionAdministradorActionPerformed
        IniciarSesionAdministrador formularioIniciarSesionAdministrador = new IniciarSesionAdministrador(this, true);
        formularioIniciarSesionAdministrador.setVisible(true);
        String usuario = formularioIniciarSesionAdministrador.getUsuario();
        String contraseña = formularioIniciarSesionAdministrador.getContraseña();
        boolean resultado;
        try {
            resultado = LaNubia.IniciarSesionAdministrador(usuario, contraseña);
            if (resultado == true) {
                Administrador formularioInicioSesionAdministrador = new Administrador(null, true, this.LaNubia);
                formularioInicioSesionAdministrador.setVisible(true);
            }
        } catch (MisExcepciones ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error "+ex);
        }

    }//GEN-LAST:event_btnIniciarSesionAdministradorActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        cargar();
    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AeropuertoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AeropuertoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AeropuertoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AeropuertoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AeropuertoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIniciarSesionAdministrador;
    private javax.swing.JButton btnIniciarSesionClientes;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JLabel lblCargarYGuardar;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblLaNubia;
    // End of variables declaration//GEN-END:variables
}
