/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.AeropuertoControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class ClienteNormal extends javax.swing.JDialog {

    /**
     * Creates new form ClienteNormal
     */
    AeropuertoControlador LaNubia;

    public ClienteNormal(java.awt.Frame parent, boolean modal, AeropuertoControlador LaNubia) {
        super(parent, modal);
        initComponents();
        this.LaNubia = LaNubia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClienteNormal = new javax.swing.JLabel();
        btnConsultarDestinos = new javax.swing.JButton();
        btnConsultarVueloA = new javax.swing.JButton();
        btnConsultarVueloB = new javax.swing.JButton();
        btnConsultarPrecios = new javax.swing.JButton();
        btnReservarTiquete = new javax.swing.JButton();
        btnEliminarReserva = new javax.swing.JButton();
        btnVerImagenDestino = new javax.swing.JButton();
        btnMostrarReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblClienteNormal.setText("Cliente Normal");

        btnConsultarDestinos.setText("Consultar Destinos");
        btnConsultarDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDestinosActionPerformed(evt);
            }
        });

        btnConsultarVueloA.setText("Consultar Vuelo A");
        btnConsultarVueloA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVueloAActionPerformed(evt);
            }
        });

        btnConsultarVueloB.setText("Consultar Vuelo B");
        btnConsultarVueloB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVueloBActionPerformed(evt);
            }
        });

        btnConsultarPrecios.setText("Consultar Precios");
        btnConsultarPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPreciosActionPerformed(evt);
            }
        });

        btnReservarTiquete.setText("Reservar Tiquete");
        btnReservarTiquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarTiqueteActionPerformed(evt);
            }
        });

        btnEliminarReserva.setText("Eliminar Reserva");
        btnEliminarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarReservaActionPerformed(evt);
            }
        });

        btnVerImagenDestino.setText("Ver Imagen Destino");
        btnVerImagenDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerImagenDestinoActionPerformed(evt);
            }
        });

        btnMostrarReservas.setText("Mostrar mis Reservas");
        btnMostrarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnVerImagenDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(btnEliminarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReservarTiquete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarPrecios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarVueloA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarDestinos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarVueloB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(btnMostrarReservas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblClienteNormal)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblClienteNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerImagenDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarVueloA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarVueloB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarPrecios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservarTiquete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarReserva)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDestinosActionPerformed
        MostrarDestinos MostrarDestinosCN = new MostrarDestinos(null, true, this.LaNubia);
        MostrarDestinosCN.setVisible(true);
    }//GEN-LAST:event_btnConsultarDestinosActionPerformed

    private void btnConsultarVueloAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVueloAActionPerformed
        ConsultarVueloA VuelosA = new ConsultarVueloA(null, true, this.LaNubia);
        VuelosA.setVisible(true);
    }//GEN-LAST:event_btnConsultarVueloAActionPerformed

    private void btnConsultarPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPreciosActionPerformed
        ConsultarPrecios verPreciosCN = new ConsultarPrecios(null, true, this.LaNubia);
        verPreciosCN.setVisible(true);
    }//GEN-LAST:event_btnConsultarPreciosActionPerformed

    private void btnConsultarVueloBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVueloBActionPerformed
        ConsultarVueloB VuelosB = new ConsultarVueloB(null, true, this.LaNubia);
        VuelosB.setVisible(true);
    }//GEN-LAST:event_btnConsultarVueloBActionPerformed

    private void btnMostrarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReservasActionPerformed
        ConsultarReserva menu = new ConsultarReserva(null, true, this.LaNubia);
        menu.setVisible(true);
    }//GEN-LAST:event_btnMostrarReservasActionPerformed

    private void btnReservarTiqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarTiqueteActionPerformed
        ReservarTiquete reservas = new ReservarTiquete(null, true, this.LaNubia);
        reservas.setVisible(true);
    }//GEN-LAST:event_btnReservarTiqueteActionPerformed

    private void btnEliminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReservaActionPerformed
        EliminarReserva eliminar = new EliminarReserva(null,true,this.LaNubia);
        eliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarReservaActionPerformed

    private void btnVerImagenDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerImagenDestinoActionPerformed
         VerImagenDestino Imagen = new VerImagenDestino (null,true);
         Imagen.setVisible(true);
    }//GEN-LAST:event_btnVerImagenDestinoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarDestinos;
    private javax.swing.JButton btnConsultarPrecios;
    private javax.swing.JButton btnConsultarVueloA;
    private javax.swing.JButton btnConsultarVueloB;
    private javax.swing.JButton btnEliminarReserva;
    private javax.swing.JButton btnMostrarReservas;
    private javax.swing.JButton btnReservarTiquete;
    private javax.swing.JButton btnVerImagenDestino;
    private javax.swing.JLabel lblClienteNormal;
    // End of variables declaration//GEN-END:variables
}
