/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Daniel
 */
public class VerImagenDestino extends javax.swing.JDialog {

    /**
     * Creates new form VerImageneDestino
     */
    
    int codigoDestino;
    
    public VerImagenDestino(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public int getCodigoDestino(){
        return codigoDestino;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoDestino = new javax.swing.JLabel();
        txtCodigoDestino = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        verDestinos2 = new Vistas.VerDestinos();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCodigoDestino.setText("Codigo del destino:");

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        verDestinos2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout verDestinos2Layout = new javax.swing.GroupLayout(verDestinos2);
        verDestinos2.setLayout(verDestinos2Layout);
        verDestinos2Layout.setHorizontalGroup(
            verDestinos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        verDestinos2Layout.setVerticalGroup(
            verDestinos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(verDestinos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblCodigoDestino)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnVer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoDestino)
                    .addComponent(txtCodigoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verDestinos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        codigoDestino = Integer.parseInt(txtCodigoDestino.getText());
        if (codigoDestino == 201) {
            verDestinos2.setImagen("Imagenes\\NuevaYork.jpg");
            verDestinos2.repaint();
            
        }
        if (codigoDestino == 202) {
            verDestinos2.setImagen("Imagenes\\Berlin.jpg");
            verDestinos2.repaint();
        }
        if (codigoDestino == 203) {
            verDestinos2.setImagen("Imagenes\\Londres.jpg");
            verDestinos2.repaint();
        }
        if (codigoDestino == 204) {
            verDestinos2.setImagen("Imagenes\\Sidney.jpg");
            verDestinos2.repaint();
        }
        if (codigoDestino == 205) {
            verDestinos2.setImagen("Imagenes\\Chamonix.jpg");
            verDestinos2.repaint();
        }
        if (codigoDestino == 206) {
            verDestinos2.setImagen("Imagenes\\Praga.jpg");
            verDestinos2.repaint();
        }
        if (codigoDestino == 207) {
            verDestinos2.setImagen("Imagenes\\Reikiavik.jpg");
            verDestinos2.repaint();
        }
        if (codigoDestino == 208) {
            verDestinos2.setImagen("Imagenes\\Habana.jpg");
            verDestinos2.repaint();
        }
        if (codigoDestino == 209) {
            verDestinos2.setImagen("Imagenes\\Dublin.jpg");
            verDestinos2.repaint();
        }
        if (codigoDestino == 210) {
            verDestinos2.setImagen("Imagenes\\SanDiego.jpg");
            verDestinos2.repaint();
        }
        
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigoDestino;
    private javax.swing.JTextField txtCodigoDestino;
    private Vistas.VerDestinos verDestinos2;
    // End of variables declaration//GEN-END:variables
}
